;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.charts
  "Mantine @mantine/charts 9.4.1 wrappers (generated)."
  (:require
   #?@(:cljs [["@mantine/charts" :refer [AreaChart BarChart BarsList BubbleChart ChartLegend ChartTooltip CompositeChart DonutChart FunnelChart Heatmap LineChart PieChart RadarChart RadialBarChart SankeyChart ScatterChart Sparkline Treemap]]])
   [mantine.impl.factory :as f]))

(def area-chart
  "AreaChart — Area chart component with stacked, percent and split variants

https://mantine.dev/charts/area-chart

Props (docgen 9.4.1):

- **activeDotProps** `MantineChartDotProps` — Props passed down to all active dots. Ignored if `withDots={false}` is set.
- **areaChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `AreaChart` component
- **areaProps** `((series: AreaChartSeries) => Partial<Omit<Props<any, any>, \"ref\">>) | Partial<Omit<Props<any, any>, \"ref\">>` — Props passed down to recharts `Area` component
- **children** `React.ReactNode` — Additional components that are rendered inside recharts `AreaChart` component
- **connectNulls** `boolean` _(default `true`)_ — If set, points with `null` values are connected
- **curveType** `AreaChartCurveType` _(default `'monotone'`)_ — Type of the curve
- **data** `ChartData` **(required)** — Data used to display chart
- **dataKey** `string` **(required)** — Key of the `data` object for x-axis values
- **dotProps** `MantineChartDotProps` — Props passed down to all dots. Ignored if `withDots={false}` is set.
- **fillOpacity** `number` _(default `0.2`)_ — Controls fill opacity of all areas
- **gridAxis** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which lines should be displayed in the grid, `'x'` by default
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **gridProps** `RechartsProps` — Props passed down to the `CartesianGrid` component
- **legendProps** `RechartsProps` — Props passed down to the `Legend` component
- **orientation** `\"horizontal\" | \"vertical\"` — Chart orientation, `'horizontal'` by default
- **referenceLines** `ChartReferenceLineProps[]` — Reference lines that should be displayed on the chart
- **rightYAxisLabel** `string` — A label to display next to the right y-axis
- **rightYAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component rendered on the right side
- **series** `AreaChartSeries[]` **(required)** — An array of objects with `name` and `color` keys. Determines which data should be consumed from the `data` array.
- **splitColors** `[MantineColor, MantineColor]` _(default `['green.7', 'red.7']`)_ — A tuple of colors used when `type=\"split\"` is set, ignored in all other cases. A tuple may include theme colors reference or any valid CSS colors
- **splitOffset** `number` — Offset for the split gradient. By default, value is inferred from `data` and `series` if possible. Must be generated from the data array with `getSplitOffset` function.
- **strokeDasharray** `string | number` — Dash array for the grid lines and cursor, `'5 5'` by default
- **strokeWidth** `number` _(default `2`)_ — Stroke width for the chart areas
- **textColor** `MantineColor` — Color of the text displayed inside the chart, `'dimmed'` by default
- **tickLine** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which axis should have tick line, `'y'` by default
- **tooltipAnimationDuration** `number` — Tooltip position animation duration in ms, `0` by default
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **type** `AreaChartType` _(default `'default'`)_ — Controls how chart areas are positioned relative to each other
- **unit** `string` — Unit displayed next to each tick in y-axis
- **valueFormatter** `(value: number) => string` — A function to format values on Y axis and inside the tooltip
- **withDots** `boolean` _(default `true`)_ — Determines whether dots should be displayed
- **withGradient** `boolean` _(default `false`)_ — Determines whether the chart area should be represented with a gradient instead of the solid color
- **withLegend** `boolean` — Determines whether chart legend should be displayed, `false` by default
- **withPointLabels** `boolean` _(default `false`)_ — If set, each point has an associated label
- **withRightYAxis** `boolean` — Determines whether additional y-axis should be displayed on the right side of the chart, `false` by default
- **withTooltip** `boolean` — Determines whether chart tooltip should be displayed, `true` by default
- **withXAxis** `boolean` — Determines whether x-axis should be displayed, `true` by default
- **withYAxis** `boolean` — Determines whether y-axis should be displayed, `true` by default
- **xAxisLabel** `string` — A label to display below the x-axis
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisLabel** `string` — A label to display next to the y-axis
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory AreaChart)
     :clj (f/not-implemented "mantine.charts/area-chart")))

(def bar-chart
  "BarChart — Bar chart component with stacked and percent variants

https://mantine.dev/charts/bar-chart

Props (docgen 9.4.1):

- **barChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `BarChart` component
- **barLabelColor** `MantineColor` — Controls color of the bar label, by default the value is determined by the chart orientation
- **barProps** `((series: BarChartSeries) => Partial<Omit<Props, \"ref\">>) | Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Bar` component
- **children** `React.ReactNode` — Additional components that are rendered inside recharts `BarChart` component
- **cursorFill** `MantineColor` — Fill of hovered bar section, by default value is based on color scheme
- **data** `Record<string, any>[]` **(required)** — Data used to display chart.
- **dataKey** `string` **(required)** — Key of the `data` object for x-axis values
- **fillOpacity** `number` _(default `1`)_ — Controls fill opacity of all bars
- **getBarColor** `(value: number, series: BarChartSeries) => DefaultMantineColor` — A function to assign dynamic bar color based on its value
- **gridAxis** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which lines should be displayed in the grid, `'x'` by default
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **gridProps** `RechartsProps` — Props passed down to the `CartesianGrid` component
- **legendProps** `RechartsProps` — Props passed down to the `Legend` component
- **maxBarWidth** `number` — Maximum bar width in px
- **minBarSize** `number` _(default `0`)_ — Sets minimum height of the bar in px
- **orientation** `\"horizontal\" | \"vertical\"` — Chart orientation, `'horizontal'` by default
- **referenceLines** `ChartReferenceLineProps[]` — Reference lines that should be displayed on the chart
- **rightYAxisLabel** `string` — A label to display next to the right y-axis
- **rightYAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component rendered on the right side
- **series** `BarChartSeries[]` **(required)** — An array of objects with `name` and `color` keys. Determines which data should be consumed from the `data` array.
- **strokeDasharray** `string | number` — Dash array for the grid lines and cursor, `'5 5'` by default
- **textColor** `MantineColor` — Color of the text displayed inside the chart, `'dimmed'` by default
- **tickLine** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which axis should have tick line, `'y'` by default
- **tooltipAnimationDuration** `number` — Tooltip position animation duration in ms, `0` by default
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **type** `BarChartType` _(default `'default'`)_ — Controls how bars are positioned relative to each other
- **unit** `string` — Unit displayed next to each tick in y-axis
- **valueFormatter** `(value: number) => string` — A function to format values on Y axis and inside the tooltip
- **valueLabelProps** `((series: BarChartSeries) => Partial<Omit<Props, \"ref\">>) | Partial<Props>` — Props passed down to recharts `LabelList` component
- **withBarValueLabel** `boolean` _(default `false`)_ — Determines whether a label with bar value should be displayed on top of each bar, incompatible with `type=\"stacked\"` and `type=\"percent\"`
- **withLegend** `boolean` — Determines whether chart legend should be displayed, `false` by default
- **withRightYAxis** `boolean` — Determines whether additional y-axis should be displayed on the right side of the chart, `false` by default
- **withTooltip** `boolean` — Determines whether chart tooltip should be displayed, `true` by default
- **withXAxis** `boolean` — Determines whether x-axis should be displayed, `true` by default
- **withYAxis** `boolean` — Determines whether y-axis should be displayed, `true` by default
- **xAxisLabel** `string` — A label to display below the x-axis
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisLabel** `string` — A label to display next to the y-axis
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory BarChart)
     :clj (f/not-implemented "mantine.charts/bar-chart")))

(def bars-list
  "BarsList — Display a list of bars with names and values

https://mantine.dev/charts/bars-list

Props (docgen 9.4.1):

- **autoContrast** `boolean` — If set, adjusts text color based on background color
- **barColor** `MantineColor` — Default bar background color, used when item does not have color specified
- **barGap** `MantineSpacing` _(default `5`)_ — Controls gap between bars
- **barHeight** `string | number` _(default `32`)_ — Bar height
- **barTextColor** `MantineColor` — Bar text color, overrides autoContrast
- **barsLabel** `string` — Label displayed above the bars column
- **data** `BarsListBarData[]` **(required)** — Data for bars
- **getBarProps** `(data: BarsListBarData) => DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>` — Function to pass props down to the bar depending on the bar data payload
- **minBarSize** `string | number` _(default `100`)_ — Minimum bar width
- **renderBar** `(data: BarsListBarData, defaultBar: ReactNode) => ReactNode` — Function to completely customize bar rendering
- **valueFormatter** `(value: number) => string` — Function to format value display
- **valueLabel** `string` — Label displayed above the values column

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory BarsList)
     :clj (f/not-implemented "mantine.charts/bars-list")))

(def bubble-chart
  "BubbleChart — Bubble chart component

https://mantine.dev/charts/bubble-chart

Props (docgen 9.4.1):

- **color** `MantineColor` _(default `blue.6`)_ — Color of the chart items. Key of `theme.colors` or any valid CSS color.
- **data** `Record<string, any>[]` **(required)** — Chart data
- **dataKey** `BubbleChartDataKey` **(required)** — Data keys for x, y and z axis
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **label** `string` — Chart label displayed next to the x axis
- **range** `[number, number]` **(required)** — Z axis range
- **scatterProps** `Partial<Omit<Props, \"ref\">>` — Props passed down to the `Scatter` component
- **textColor** `MantineColor` _(default `'dimmed'`)_ — Color of the text displayed inside the chart
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **valueFormatter** `(value: number) => string` — Function to format z axis values
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component
- **zAxisProps** `Omit<Props<any, any>, \"ref\">` — Props passed down to the `ZAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory BubbleChart)
     :clj (f/not-implemented "mantine.charts/bubble-chart")))

(def chart-legend
  "ChartLegend

Props (docgen 9.4.1):

- **centered** `boolean` _(default `false`)_ — Determines whether the legend should be centered
- **legendPosition** `\"bottom\" | \"top\" | \"middle\"` **(required)** — Position of the legend relative to the chart, used to apply margin on the corresponding side
- **onHighlight** `(area: string | number | null) => void` **(required)** — Function called when mouse enters/leaves one of the legend items
- **payload** `readonly Record<string, any>[]` **(required)** — Chart data provided by recharts
- **series** `ChartSeries[]` — Data used for labels, only applicable for area charts: AreaChart, LineChart, BarChart
- **showColor** `boolean` _(default `true`)_ — Determines whether color swatch should be shown next to the label

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory ChartLegend)
     :clj (f/not-implemented "mantine.charts/chart-legend")))

(def chart-tooltip
  "ChartTooltip

Props (docgen 9.4.1):

- **label** `React.ReactNode` — Main tooltip label
- **payload** `Record<string, any>[] | readonly Record<string, any>[]` **(required)** — Chart data provided by recharts
- **segmentId** `string | number` — Segment to display data for, identified by its index in the data array (preferred, isolates duplicate names) or by its name. Only applicable when `type=\"radial\"`. If not set, all data is rendered.
- **series** `ChartSeries[]` — Chart series data, applicable only for `area` type
- **showColor** `boolean` _(default `true`)_ — Determines whether the color swatch should be visible
- **type** `\"area\" | \"radial\" | \"scatter\"` _(default `'area'`)_ — Tooltip type that determines the content and styles, `area` for LineChart, AreaChart and BarChart, `radial` for DonutChart and PieChart
- **unit** `string` — Data units, provided by parent component
- **valueFormatter** `(value: number) => ReactNode` — A function to format values

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory ChartTooltip)
     :clj (f/not-implemented "mantine.charts/chart-tooltip")))

(def composite-chart
  "CompositeChart — Composed chart with support for Area, Bar and Line charts

https://mantine.dev/charts/composite-chart

Props (docgen 9.4.1):

- **activeDotProps** `MantineChartDotProps` — Props passed down to all active dots. Ignored if `withDots={false}` is set.
- **areaProps** `Partial<Omit<Props<any, any>, \"ref\">> | ((series: CompositeChartSeries) => Partial<Omit<Props<any, any>, \"ref\">>)` — Props passed down to recharts `Area` component
- **barProps** `Partial<Omit<Props, \"ref\">> | ((series: CompositeChartSeries) => Partial<Omit<Props, \"ref\">>)` — Props passed down to recharts `Bar` component
- **children** `React.ReactNode` — Additional components that are rendered inside recharts `AreaChart` component
- **composedChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `AreaChart` component
- **connectNulls** `boolean` _(default `true`)_ — Determines whether points with `null` values should be connected
- **curveType** `CompositeChartCurveType` _(default `'monotone'`)_ — Type of the curve
- **data** `Record<string, any>[]` **(required)** — Data used to display chart
- **dataKey** `string` **(required)** — Key of the `data` object for x-axis values
- **dotProps** `MantineChartDotProps` — Props passed down to all dots. Ignored if `withDots={false}` is set.
- **gridAxis** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which lines should be displayed in the grid, `'x'` by default
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **gridProps** `RechartsProps` — Props passed down to the `CartesianGrid` component
- **legendProps** `RechartsProps` — Props passed down to the `Legend` component
- **lineProps** `((series: CompositeChartSeries) => Partial<Omit<Props, \"ref\">>) | Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Line` component
- **maxBarWidth** `number` — Maximum bar width in px
- **minBarSize** `number` _(default `0`)_ — Sets minimum height of the bar in px
- **referenceLines** `ChartReferenceLineProps[]` — Reference lines that should be displayed on the chart
- **rightYAxisLabel** `string` — A label to display next to the right y-axis
- **rightYAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component rendered on the right side
- **series** `CompositeChartSeries[]` **(required)** — An array of objects with `name` and `color` keys. Determines which data should be consumed from the `data` array.
- **strokeDasharray** `string | number` — Dash array for the grid lines and cursor, `'5 5'` by default
- **strokeWidth** `number` _(default `2`)_ — Stroke width for the chart lines
- **textColor** `MantineColor` — Color of the text displayed inside the chart, `'dimmed'` by default
- **tickLine** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which axis should have tick line, `'y'` by default
- **tooltipAnimationDuration** `number` — Tooltip position animation duration in ms, `0` by default
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **unit** `string` — Unit displayed next to each tick in y-axis
- **valueFormatter** `(value: number) => string` — A function to format values on Y axis and inside the tooltip
- **withBarValueLabel** `boolean` _(default `false`)_ — Determines whether a label with bar value should be displayed on top of each bar
- **withDots** `boolean` _(default `true`)_ — Determines whether dots should be displayed
- **withLegend** `boolean` — Determines whether chart legend should be displayed, `false` by default
- **withPointLabels** `boolean` _(default `false`)_ — Determines whether each point should have associated label
- **withRightYAxis** `boolean` — Determines whether additional y-axis should be displayed on the right side of the chart, `false` by default
- **withTooltip** `boolean` — Determines whether chart tooltip should be displayed, `true` by default
- **withXAxis** `boolean` — Determines whether x-axis should be displayed, `true` by default
- **withYAxis** `boolean` — Determines whether y-axis should be displayed, `true` by default
- **xAxisLabel** `string` — A label to display below the x-axis
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisLabel** `string` — A label to display next to the y-axis
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory CompositeChart)
     :clj (f/not-implemented "mantine.charts/composite-chart")))

(def donut-chart
  "DonutChart — Donut chart component

https://mantine.dev/charts/donut-chart

Props (docgen 9.4.1):

- **cellProps** `((series: DonutChartCell) => Partial<Omit<SVGProps<SVGElement>, \"ref\">>) | Partial<Omit<SVGProps<SVGElement>, \"ref\">>` — Props passed down to each segment of the chart
- **chartLabel** `string | number` — Chart label, displayed in the center of the chart
- **children** `React.ReactNode` — Additional elements rendered inside `PieChart` component
- **data** `DonutChartCell[]` **(required)** — Data used to render chart
- **endAngle** `number` _(default `360`)_ — Controls angle at which charts ends. Set to `0` to render the chart as semicircle.
- **labelColor** `MantineColor` — Controls text color of all labels, by default depends on color scheme
- **labelsType** `\"value\" | \"name\" | \"percent\"` — Type of labels to display, `'value'` by default
- **legendProps** `RechartsProps` — Props passed down to recharts `Legend` component
- **paddingAngle** `number` _(default `0`)_ — Controls padding between segments
- **pieChartProps** `(PolarChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `PieChart` component
- **pieProps** `Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Pie` component
- **size** `number` _(default `80`)_ — Controls chart width and height, height is increased by 40 if `withLabels` prop is set. Cannot be less than `thickness`.
- **startAngle** `number` _(default `0`)_ — Controls angle at which chart starts. Set to `180` to render the chart as semicircle.
- **strokeColor** `MantineColor` — Controls color of the segments stroke, by default depends on color scheme
- **strokeWidth** `number` _(default `1`)_ — Controls width of segments stroke
- **thickness** `number` _(default `20`)_ — Controls thickness of the chart segments
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip animation duration in ms
- **tooltipDataSource** `\"all\" | \"segment\"` _(default `'all'`)_ — Determines which data is displayed in the tooltip. `'all'` – display all values, `'segment'` – display only hovered segment.
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **valueFormatter** `(value: number) => string` — A function to format values inside the tooltip
- **withLabels** `boolean` _(default `false`)_ — Determines whether each segment should have associated label
- **withLabelsLine** `boolean` _(default `true`)_ — Determines whether segments labels should have lines that connect the segment with the label
- **withLegend** `boolean` _(default `false`)_ — Determines whether the legend should be displayed
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when one of the section is hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory DonutChart)
     :clj (f/not-implemented "mantine.charts/donut-chart")))

(def funnel-chart
  "FunnelChart — Funnel chart component

https://mantine.dev/charts/funnel-chart

Props (docgen 9.4.1):

- **children** `React.ReactNode` — Additional elements rendered inside `FunnelChart` component
- **data** `FunnelChartCell[]` **(required)** — Data used to render chart
- **funnelChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `FunnelChart` component
- **funnelProps** `Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Pie` component
- **labelColor** `MantineColor` _(default `'white'`)_ — Controls text color of all labels
- **labelsPosition** `\"left\" | \"right\" | \"inside\"` _(default `'right'`)_ — Controls labels position relative to the segment
- **legendProps** `RechartsProps` — Props passed down to recharts `Legend` component
- **size** `number` _(default `300`)_ — Controls chart width and height
- **strokeColor** `MantineColor` — Controls color of the segments stroke, by default depends on color scheme
- **strokeWidth** `number` _(default `1`)_ — Controls width of segments stroke
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip animation duration in ms
- **tooltipDataSource** `\"all\" | \"segment\"` _(default `'all'`)_ — Determines which data is displayed in the tooltip. `'all'` – display all values, `'segment'` – display only hovered segment.
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **valueFormatter** `(value: number) => string` — A function to format values inside the tooltip and labels
- **withLabels** `boolean` _(default `false`)_ — Determines whether each segment should have associated label
- **withLegend** `boolean` _(default `false`)_ — Determines whether the legend should be displayed
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when a section is hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory FunnelChart)
     :clj (f/not-implemented "mantine.charts/funnel-chart")))

(def heatmap
  "Heatmap — Heatmap chart component

https://mantine.dev/charts/heatmap

Props (docgen 9.4.1):

- **colors** `string[]` — Colors array, used to calculate color for each value, by default 4 shades of green colors are used
- **data** `Record<string, number>` **(required)** — Heatmap data, key is date in `YYYY-MM-DD` format (interpreted as a UTC calendar day)
- **domain** `[number, number]` — Heatmap domain, array of 2 numbers, min and max values, calculated from data by default
- **endDate** `string | Date` — Heatmap end date. Current date by default. Date is normalized to UTC midnight of the intended calendar day.
- **firstDayOfWeek** `0 | 2 | 1 | 3 | 4 | 5 | 6` _(default `1 – Monday`)_ — First day of week, 0 – Sunday, 1 – Monday.
- **fontSize** `number` _(default `12`)_ — Font size of month and weekday labels
- **gap** `number` _(default `1`)_ — Gap between rects in px
- **getRectProps** `(input: HeatmapRectData) => SVGProps<SVGRectElement>` — Props passed down to each rect depending on its date and associated value
- **getTooltipLabel** `(input: HeatmapRectData) => ReactNode` — A function to generate tooltip label based on the hovered rect date and value, required for the tooltip to be visible
- **legendLabels** `[string, string]` _(default `['Less', 'More']`)_ — Legend labels, array of 2 elements: [min label, max label]
- **monthLabels** `string[]` — Month labels, array of 12 elements, can be used for localization
- **monthsLabelsHeight** `number` _(default `30`)_ — Height of month labels row
- **rectRadius** `number` _(default `2`)_ — Rect radius in px
- **rectSize** `number` _(default `10`)_ — Size of day rect in px
- **splitMonths** `boolean` _(default `false`)_ — If set, inserts a spacer column between months
- **startDate** `string | Date` — Heatmap start date. Current date - 1 year by default. Date is normalized to UTC midnight of the intended calendar day.
- **tooltipProps** `Partial<TooltipFloatingProps>` — Props passed down to the `Tooltip.Floating` component
- **weekdayLabels** `string[]` — Weekday labels, array of 7 elements, can be used for localization
- **weekdaysLabelsWidth** `number` _(default `30`)_ — Width of weekday labels column
- **withLegend** `boolean` _(default `false`)_ — If set, legend with color levels is displayed below the heatmap
- **withMonthLabels** `boolean` _(default `false`)_ — If set, month labels are displayed
- **withOutsideDates** `boolean` _(default `true`)_ — If set, trailing dates that do not fall into the given `startDate` – `endDate` range are displayed to fill empty space.
- **withTooltip** `boolean` _(default `false`)_ — If set, tooltip is displayed on rect hover
- **withWeekdayLabels** `boolean` _(default `false`)_ — If set, weekday labels are displayed

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Heatmap)
     :clj (f/not-implemented "mantine.charts/heatmap")))

(def line-chart
  "LineChart — Line chart component

https://mantine.dev/charts/line-chart

Props (docgen 9.4.1):

- **activeDotProps** `MantineChartDotProps` — Props passed down to all active dots. Ignored if `withDots={false}` is set.
- **children** `React.ReactNode` — Additional components that are rendered inside recharts `LineChart` component
- **connectNulls** `boolean` _(default `true`)_ — Determines whether points with `null` values should be connected
- **curveType** `LineChartCurveType` _(default `'monotone'`)_ — Type of the curve
- **data** `Record<string, any>[]` **(required)** — Data used to display chart
- **dataKey** `string` **(required)** — Key of the `data` object for x-axis values
- **dotProps** `MantineChartDotProps` — Props passed down to all dots. Ignored if `withDots={false}` is set.
- **fillOpacity** `number` _(default `1`)_ — Controls fill opacity of all lines
- **gradientStops** `LineChartGradientStop[]` _(default `[{ offset: 0, color: 'red' }, { offset: 100, color: 'blue' }]`)_ — Data used to generate gradient stops
- **gridAxis** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which lines should be displayed in the grid, `'x'` by default
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **gridProps** `RechartsProps` — Props passed down to the `CartesianGrid` component
- **legendProps** `RechartsProps` — Props passed down to the `Legend` component
- **lineChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `LineChart` component
- **lineProps** `Partial<Omit<Props, \"ref\">> | ((series: LineChartSeries) => Partial<Omit<Props, \"ref\">>)` — Props passed down to recharts `Line` component
- **orientation** `\"horizontal\" | \"vertical\"` — Chart orientation, `'horizontal'` by default
- **referenceLines** `ChartReferenceLineProps[]` — Reference lines that should be displayed on the chart
- **rightYAxisLabel** `string` — A label to display next to the right y-axis
- **rightYAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component rendered on the right side
- **series** `LineChartSeries[]` **(required)** — An array of objects with `name` and `color` keys. Determines which data should be consumed from the `data` array.
- **strokeDasharray** `string | number` — Dash array for the grid lines and cursor, `'5 5'` by default
- **strokeWidth** `number` _(default `2`)_ — Stroke width for the chart lines
- **textColor** `MantineColor` — Color of the text displayed inside the chart, `'dimmed'` by default
- **tickLine** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which axis should have tick line, `'y'` by default
- **tooltipAnimationDuration** `number` — Tooltip position animation duration in ms, `0` by default
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **type** `LineChartType` _(default `'default'`)_ — Controls styles of the line
- **unit** `string` — Unit displayed next to each tick in y-axis
- **valueFormatter** `(value: number) => string` — A function to format values on Y axis and inside the tooltip
- **withDots** `boolean` _(default `true`)_ — Determines whether dots should be displayed
- **withLegend** `boolean` — Determines whether chart legend should be displayed, `false` by default
- **withPointLabels** `boolean` _(default `false`)_ — Determines whether each point should have associated label
- **withRightYAxis** `boolean` — Determines whether additional y-axis should be displayed on the right side of the chart, `false` by default
- **withTooltip** `boolean` — Determines whether chart tooltip should be displayed, `true` by default
- **withXAxis** `boolean` — Determines whether x-axis should be displayed, `true` by default
- **withYAxis** `boolean` — Determines whether y-axis should be displayed, `true` by default
- **xAxisLabel** `string` — A label to display below the x-axis
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisLabel** `string` — A label to display next to the y-axis
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory LineChart)
     :clj (f/not-implemented "mantine.charts/line-chart")))

(def pie-chart
  "PieChart — Pie chart component

https://mantine.dev/charts/pie-chart

Props (docgen 9.4.1):

- **cellProps** `Partial<Omit<SVGProps<SVGElement>, \"ref\">> | ((series: PieChartCell) => Partial<Omit<SVGProps<SVGElement>, \"ref\">>)` — Props passed down to each segment of the chart
- **children** `React.ReactNode` — Additional elements rendered inside `PieChart` component
- **data** `PieChartCell[]` **(required)** — Data used to render chart
- **endAngle** `number` _(default `360`)_ — Controls angle at which charts ends. Set to `0` to render the chart as semicircle.
- **labelColor** `MantineColor` — Controls text color of all labels, white by default
- **labelsPosition** `\"outside\" | \"inside\"` _(default `'outside'`)_ — Controls labels position relative to the segment
- **labelsType** `\"value\" | \"name\" | \"percent\"` _(default `'value'`)_ — Type of labels to display
- **legendProps** `RechartsProps` — Props passed down to recharts `Legend` component
- **paddingAngle** `number` _(default `0`)_ — Controls padding between segments
- **pieChartProps** `(PolarChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `PieChart` component
- **pieProps** `Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Pie` component
- **size** `number` _(default `80`)_ — Controls chart width and height, height is increased by 40 if `withLabels` prop is set. Cannot be less than `thickness`.
- **startAngle** `number` _(default `0`)_ — Controls angle at which chart starts. Set to `180` to render the chart as semicircle.
- **strokeColor** `MantineColor` — Controls color of the segments stroke, by default depends on color scheme
- **strokeWidth** `number` _(default `1`)_ — Controls width of segments stroke
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip animation duration in ms
- **tooltipDataSource** `\"all\" | \"segment\"` _(default `'all'`)_ — Determines which data is displayed in the tooltip. `'all'` – display all values, `'segment'` – display only hovered segment.
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **valueFormatter** `(value: number) => string` — A function to format values inside the tooltip
- **withLabels** `boolean` _(default `false`)_ — Determines whether each segment should have associated label
- **withLabelsLine** `boolean` _(default `true`)_ — Determines whether segments labels should have lines that connect the segment with the label
- **withLegend** `boolean` _(default `false`)_ — Determines whether the legend should be displayed
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when one of the section is hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory PieChart)
     :clj (f/not-implemented "mantine.charts/pie-chart")))

(def radar-chart
  "RadarChart — Radar chart component

https://mantine.dev/charts/radar-chart

Props (docgen 9.4.1):

- **activeDotProps** `MantineChartDotProps` — Props passed down to all active dots. Ignored if `withDots={false}` is set.
- **children** `React.ReactNode` — Additional components that are rendered inside recharts `RadarChart` component
- **data** `Record<string, any>[]` **(required)** — Data used in the chart
- **dataKey** `string` **(required)** — Key of the `data` object for axis values
- **dotProps** `MantineChartDotProps` — Props passed down to all dots. Ignored if `withDots={false}` is set.
- **gridColor** `MantineColor` — Controls color of the grid lines. By default, color depends on the color scheme.
- **legendProps** `RechartsProps` — Props passed down to recharts Legend component
- **polarAngleAxisProps** `RechartsProps` — Props passed down to recharts PolarAngleAxis component
- **polarGridProps** `RechartsProps` — Props passed down to recharts PolarGrid component
- **polarRadiusAxisProps** `RechartsProps` — Props passed down to recharts PolarRadiusAxis component
- **radarChartProps** `(PolarChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts RadarChart component
- **radarProps** `((series: RadarChartSeries) => Partial<Omit<Props, \"ref\">>) | Partial<Omit<Props, \"ref\">>` — Props passed down to recharts Radar component
- **series** `RadarChartSeries[]` **(required)** — Determines which data should be consumed from the `data` array.
- **textColor** `MantineColor` — Controls color of all text elements. By default, color depends on the color scheme.
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip position animation duration in ms
- **tooltipProps** `RechartsProps` — Props passed down to recharts Tooltip component
- **withDots** `boolean` _(default `false`)_ — Determines whether dots should be displayed
- **withLegend** `boolean` _(default `false`)_ — Determines whether the legend should be displayed
- **withPolarAngleAxis** `boolean` _(default `true`)_ — Determines whether PolarAngleAxis component should be displayed
- **withPolarGrid** `boolean` _(default `true.`)_ — Determines whether PolarGrid component should be displayed
- **withPolarRadiusAxis** `boolean` _(default `false`)_ — Determines whether PolarRadiusAxisProps component should be displayed
- **withTooltip** `boolean` _(default `false`)_ — Determines whether Tooltip component should be displayed

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory RadarChart)
     :clj (f/not-implemented "mantine.charts/radar-chart")))

(def radial-bar-chart
  "RadialBarChart — Radial bar chart component

https://mantine.dev/charts/radial-bar-chart

Props (docgen 9.4.1):

- **barSize** `number` — Size of bars in px, `20` by default
- **data** `Record<string, any>[]` **(required)** — Chart data
- **dataKey** `string` **(required)** — Key from data object to use as data key
- **emptyBackgroundColor** `string` — Color of the empty background, by default depends on the color scheme
- **endAngle** `number` _(default `-270`)_ — Angle at which chart ends
- **legendProps** `RechartsProps` — Props passed down to recharts Legend component
- **radialBarChartProps** `(PolarChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts RadarChartChart component
- **radialBarProps** `Omit<RadialBarProps, \"ref\">` — Props passed down to recharts RadialBar component
- **startAngle** `number` _(default `90`)_ — Angle at which chart starts
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **withBackground** `boolean` _(default `true`)_ — Determines whether empty bars area should be visible
- **withLabels** `boolean` _(default `false`)_ — Determines whether labels should be displayed
- **withLegend** `boolean` _(default `false`)_ — Determines whether the legend should be displayed
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when one of the bars is hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory RadialBarChart)
     :clj (f/not-implemented "mantine.charts/radial-bar-chart")))

(def sankey-chart
  "SankeyChart — Sankey diagram component

https://mantine.dev/charts/sankey-chart

Props (docgen 9.4.1):

- **children** `React.ReactNode` — Additional elements rendered inside `Sankey` component
- **colors** `DefaultMantineColor[]` — An array of colors used for nodes when no `color` is set on individual nodes
- **data** `SankeyChartData` **(required)** — Data used to render chart, must include `nodes` and `links` arrays
- **height** `number` _(default `300`)_ — Controls chart height
- **iterations** `number` _(default `32`)_ — The number of relaxation iterations
- **linkColor** `MantineColor` — Default color for links, by default depends on color scheme
- **linkCurvature** `number` _(default `0.5`)_ — The curvature of links between nodes
- **linkOpacity** `number` _(default `0.4`)_ — Opacity of the link fill
- **nodeColor** `MantineColor` — Default color for nodes, by default depends on color scheme
- **nodePadding** `number` _(default `10`)_ — The padding between nodes
- **nodeWidth** `number` _(default `10`)_ — The width of each node
- **sankeyProps** `Partial<Omit<Props, \"data\" | \"ref\">>` — Props passed down to recharts `Sankey` component
- **textColor** `MantineColor` _(default `dimmed`)_ — Controls text color of labels
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip animation duration in ms
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **valueFormatter** `(value: number) => string` — A function to format values inside the tooltip and node labels
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory SankeyChart)
     :clj (f/not-implemented "mantine.charts/sankey-chart")))

(def scatter-chart
  "ScatterChart — Scatter chart component

https://mantine.dev/charts/scatter-chart

Props (docgen 9.4.1):

- **data** `ScatterChartSeries[]` **(required)** — Data that is used to build the chart
- **dataKey** `{ x: string; y: string; }` **(required)** — Keys that should be used to retrieve data from the data array on x and y axis
- **gridAxis** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which lines should be displayed in the grid, `'x'` by default
- **gridColor** `MantineColor` — Color of the grid and cursor lines, by default depends on color scheme
- **gridProps** `RechartsProps` — Props passed down to the `CartesianGrid` component
- **labels** `{ x?: string; y?: string | undefined; } | undefined` — Labels that should be used instead of keys names in the tooltip
- **legendProps** `RechartsProps` — Props passed down to the `Legend` component
- **orientation** `\"horizontal\" | \"vertical\"` — Chart orientation, `'horizontal'` by default
- **pointLabels** `\"x\" | \"y\"` — If set, displays labels next to points for the given axis
- **referenceLines** `ChartReferenceLineProps[]` — Reference lines that should be displayed on the chart
- **rightYAxisLabel** `string` — A label to display next to the right y-axis
- **rightYAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component rendered on the right side
- **scatterChartProps** `(CartesianChartProps<unknown> & { ref?: Ref<SVGSVGElement>; }) | undefined` — Props passed down to recharts `ScatterChart` component
- **scatterProps** `Partial<Omit<Props, \"ref\">>` — Props passed down to recharts `Scatter` component
- **strokeDasharray** `string | number` — Dash array for the grid lines and cursor, `'5 5'` by default
- **textColor** `MantineColor` — Color of the text displayed inside the chart, `'dimmed'` by default
- **tickLine** `\"none\" | \"x\" | \"y\" | \"xy\"` — Specifies which axis should have tick line, `'y'` by default
- **tooltipAnimationDuration** `number` — Tooltip position animation duration in ms, `0` by default
- **tooltipProps** `RechartsProps` — Props passed down to the `Tooltip` component
- **unit** `{ x?: string; y?: string | undefined; } | undefined` — Units displayed after value on axis and inside the tooltip
- **valueFormatter** `((value: number) => string) | { x?: ((value: number) => string); y?: ((value: number) => string) | undefined; } | undefined` — A function to format values on x/y axis and in the tooltip
- **withLegend** `boolean` — Determines whether chart legend should be displayed, `false` by default
- **withRightYAxis** `boolean` — Determines whether additional y-axis should be displayed on the right side of the chart, `false` by default
- **withTooltip** `boolean` — Determines whether chart tooltip should be displayed, `true` by default
- **withXAxis** `boolean` — Determines whether x-axis should be displayed, `true` by default
- **withYAxis** `boolean` — Determines whether y-axis should be displayed, `true` by default
- **xAxisLabel** `string` — A label to display below the x-axis
- **xAxisProps** `RechartsProps` — Props passed down to the `XAxis` recharts component
- **yAxisLabel** `string` — A label to display next to the y-axis
- **yAxisProps** `RechartsProps` — Props passed down to the `YAxis` recharts component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory ScatterChart)
     :clj (f/not-implemented "mantine.charts/scatter-chart")))

(def sparkline
  "Sparkline — Simplified area chart to show trends

https://mantine.dev/charts/sparkline

Props (docgen 9.4.1):

- **areaProps** `Omit<Props<any, any>, \"data\" | \"ref\" | \"dataKey\">` — Props passed down to the underlying recharts `Area` component
- **color** `MantineColor` _(default `theme.primaryColor`)_ — Key of `theme.colors` or any valid CSS color
- **connectNulls** `boolean` _(default `true`)_ — Determines whether null values should be connected with other values
- **curveType** `AreaChartCurveType` _(default `'linear'`)_ — Type of the curve
- **data** `(number | null)[]` **(required)** — Data used to render the chart
- **fillOpacity** `number` _(default `0.6`)_ — Controls fill opacity of the area
- **strokeWidth** `number` _(default `2`)_ — Area stroke width
- **trendColors** `SparklineTrendColors` — If set, `color` prop is ignored and chart color is determined by the difference between first and last value.
- **withGradient** `boolean` _(default `true`)_ — Determines whether the chart fill should be a gradient

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Sparkline)
     :clj (f/not-implemented "mantine.charts/sparkline")))

(def treemap
  "Treemap — Treemap chart component

https://mantine.dev/charts/treemap

Props (docgen 9.4.1):

- **aspectRatio** `number` _(default `1.618033988749895`)_ — The treemap will try to keep every single rectangle's aspect ratio near the aspectRatio given
- **autoContrast** `boolean` — Determines whether text color should be adjusted based on background color to improve contrast
- **children** `React.ReactNode` — Additional elements rendered inside `Treemap` component
- **data** `TreemapData[]` **(required)** — Data used to render chart
- **dataKey** `string` _(default `'value'`)_ — Key in data object for the value
- **height** `number` _(default `300`)_ — Controls chart height
- **strokeColor** `MantineColor` — Controls color of the node stroke, by default depends on color scheme
- **strokeWidth** `number` _(default `1`)_ — Controls width of node stroke
- **textColor** `MantineColor` _(default `dimmed`)_ — Controls text color of labels
- **tooltipAnimationDuration** `number` _(default `0`)_ — Tooltip animation duration in ms
- **tooltipProps** `RechartsProps` — Props passed down to `Tooltip` recharts component
- **treemapProps** `Partial<Omit<Props<TreemapDataType, any>, \"data\" | \"ref\" | \"dataKey\">>` — Props passed down to recharts `Treemap` component
- **valueFormatter** `(value: number) => string` — A function to format values inside the tooltip
- **withTooltip** `boolean` _(default `true`)_ — Determines whether the tooltip should be displayed when a node is hovered

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Treemap)
     :clj (f/not-implemented "mantine.charts/treemap")))
