;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.core
  "Mantine @mantine/core 9.4.1 wrappers (generated)."
  (:require
   #?@(:cljs [["@mantine/core" :refer [Badge Button Collapse Group Stack Text TextInput]]])
   [mantine.impl.factory :as f]))

(def badge
  "Badge — Display badge, pill or tag

https://mantine.dev/core/badge

Polymorphic: accepts :component / :render-root.

Props (docgen 9.4.1):
  autoContrast (boolean) — If set, adjusts text color based on background color for <code>filled</code> variant
  children (React.ReactNode) — Main badge content
  circle (boolean) — If set, badge <code>min-width</code> becomes equal to its <code>height</code> and horizontal padding is removed
  color (MantineColor) [default theme.primaryColor] — Key of <code>theme.colors</code> or any valid CSS color
  fullWidth (boolean) [default false] — Determines whether Badge should take 100% of its parent width
  gradient (MantineGradient) [default theme.defaultGradient] — Gradient configuration used when <code>variant=\\\"gradient\\\"</code>
  leftSection (React.ReactNode) — Content displayed on the left side of the badge label
  radius (MantineRadius | number) [default 'xl'] — Key of <code>theme.radius</code> or any valid CSS value to set <code>border-radius</code>
  rightSection (React.ReactNode) — Content displayed on the right side of the badge label
  size (MantineSize) [default 'md'] — Controls <code>font-size</code>, <code>height</code> and horizontal <code>padding</code>

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Badge)
     :clj (f/not-implemented "mantine.core/badge")))

(def button
  "Button — Button component to render button or link

https://mantine.dev/core/button

Props (docgen 9.4.1):
  autoContrast (boolean) — If set, adjusts text color based on background color for <code>filled</code> variant
  children (React.ReactNode) — Button content
  color (MantineColor) [default theme.primaryColor] — Key of <code>theme.colors</code> or any valid CSS color
  disabled (boolean) — Sets <code>disabled</code> attribute, applies disabled styles
  fullWidth (boolean) [default false] — Sets <code>width: 100%</code>
  gradient (MantineGradient) [default theme.defaultGradient] — Gradient configuration used for <code>variant=\"gradient\"</code>
  justify (JustifyContent) [default 'center'] — Sets <code>justify-content</code> of <code>inner</code> element, can be used to change distribution of sections and label
  leftSection (React.ReactNode) — Content on the left side of the button label
  loaderProps (LoaderProps) — Props added to the <code>Loader</code> component (only visible when <code>loading</code> prop is set)
  loading (boolean) — If set, the <code>Loader</code> component is displayed over the button
  radius (MantineRadius | number) [default theme.defaultRadius] — Key of <code>theme.radius</code> or any valid CSS value to set <code>border-radius</code>
  rightSection (React.ReactNode) — Content on the right side of the button label
  size (ButtonSize) [default 'sm'] — Controls button <code>height</code>, <code>font-size</code> and horizontal <code>padding</code>

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Button)
     :clj (f/not-implemented "mantine.core/button")))

(def collapse
  "Collapse — Animate presence with slide down/up transition

https://mantine.dev/core/collapse

Props (docgen 9.4.1):
  animateOpacity (boolean) [default true] — Determines whether the opacity is animated
  expanded (boolean) REQUIRED — Expanded state
  keepMounted (boolean) [default true] — If set, the element is kept in the DOM when collapsed. When <code>true</code>, React 19 <code>Activity</code> is used to preserve state while collapsed. When <code>false</code>, the element is unmounted after the exit animation.
  onTransitionEnd (() => void) — Called when the transition ends
  onTransitionStart (() => void) — Called when transition starts
  orientation (\"horizontal\" | \"vertical\") [default 'vertical'] — Collapse orientation
  transitionDuration (number) [default 200] — Transition duration in ms
  transitionTimingFunction (string) [default ease] — Transition timing function

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Collapse)
     :clj (f/not-implemented "mantine.core/collapse")))

(def group
  "Group — Compose elements and components in a horizontal flex container

https://mantine.dev/core/group

Props (docgen 9.4.1):
  align (AlignItems) [default 'center'] — Controls <code>align-items</code> CSS property
  gap (MantineSpacing) [default 'md'] — Key of <code>theme.spacing</code> or any valid CSS value for <code>gap</code>, numbers are converted to rem
  grow (boolean) [default false] — Determines whether each child element should have <code>flex-grow: 1</code> style
  justify (JustifyContent) [default 'flex-start'] — Controls <code>justify-content</code> CSS property
  preventGrowOverflow (boolean) [default true] — Determines whether children should take only dedicated amount of space (<code>max-width</code> style is set based on the number of children)
  wrap (FlexWrap) [default 'wrap'] — Controls <code>flex-wrap</code> CSS property

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Group)
     :clj (f/not-implemented "mantine.core/group")))

(def stack
  "Stack — Compose elements and components in a vertical flex container

https://mantine.dev/core/stack

Props (docgen 9.4.1):
  align (AlignItems) [default 'stretch'] — Controls <code>align-items</code> CSS property
  gap (MantineSpacing) [default 'md'] — Key of <code>theme.spacing</code> or any valid CSS value to set <code>gap</code> property, numbers are converted to rem
  justify (JustifyContent) [default 'flex-start'] — Controls <code>justify-content</code> CSS property

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Stack)
     :clj (f/not-implemented "mantine.core/stack")))

(def text
  "Text — Display text

https://mantine.dev/core/text

Props (docgen 9.4.1):
  gradient (MantineGradient) [default theme.defaultGradient] — Gradient configuration, ignored when <code>variant</code> is not <code>gradient</code>
  inherit (boolean) [default false] — Determines whether font properties should be inherited from the parent
  inline (boolean) [default false] — Sets <code>line-height</code> to 1 for centering
  lineClamp (number) — Number of lines after which Text will be truncated
  size (MantineSize | (string & {})) [default 'md'] — Controls <code>font-size</code> and <code>line-height</code>
  span (boolean) — Shorthand for <code>component=\"span\"</code>
  textWrap (\"wrap\" | \"nowrap\" | \"balance\" | \"pretty\" | \"stable\") — Controls <code>text-wrap</code> CSS property
  truncate (TextTruncate) — Side on which Text must be truncated, if <code>true</code>, text is truncated from the start

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Text)
     :clj (f/not-implemented "mantine.core/text")))

(def text-input
  "TextInput — Capture string input from user

https://mantine.dev/core/text-input

Props (docgen 9.4.1):
  description (React.ReactNode) — Contents of <code>Input.Description</code> component. If not set, description is not displayed.
  descriptionProps (InputDescriptionProps) — Props passed down to the <code>Input.Description</code> component
  disabled (boolean) — Sets <code>disabled</code> attribute on the <code>input</code> element
  error (React.ReactNode) — Contents of <code>Input.Error</code> component. If not set, error is not displayed.
  errorProps (InputErrorProps) — Props passed down to the <code>Input.Error</code> component
  inputContainer ((children: ReactNode) => ReactNode) [default React.Fragment] — Render function to wrap the input element. Useful for adding tooltips, popovers, or other wrappers around the input.
  inputSize (string) — HTML <code>size</code> attribute for the input element (number of visible characters)
  inputWrapperOrder ((\"input\" | \"label\" | \"description\" | \"error\")[]) [default ['label', 'description', 'input', 'error']] — Controls order and visibility of wrapper elements. Only elements included in this array will be rendered.
  label (React.ReactNode) — Contents of <code>Input.Label</code> component. If not set, label is not displayed.
  labelProps (InputLabelProps) — Props passed down to the <code>Input.Label</code> component
  leftSection (React.ReactNode) — Content section displayed on the left side of the input
  leftSectionPointerEvents (React.CSSProperties[\"pointerEvents\"]) [default 'none'] — Sets <code>pointer-events</code> styles on the <code>leftSection</code> element. Use <code>'all'</code> when section contains interactive elements (buttons, links).
  leftSectionProps (React.ComponentProps<\"div\">) — Props passed down to the <code>leftSection</code> element
  leftSectionWidth (React.CSSProperties[\"width\"]) — Left section width, used to set <code>width</code> of the section and input <code>padding-left</code>, by default equals to the input height
  loading (boolean) [default false] — Displays loading indicator in the left or right section
  loadingPosition (\"left\" | \"right\") [default 'right'] — Position of the loading indicator
  pointer (boolean) [default false] — Determines whether the input should have <code>cursor: pointer</code> style. Use when input acts as a button-like trigger (e.g., <code>component=\"button\"</code> for Select/DatePicker).
  radius (MantineRadius | number) [default theme.defaultRadius] — Key of <code>theme.radius</code> or any valid CSS value to set <code>border-radius</code>, numbers are converted to rem
  required (boolean) [default false] — Adds required attribute to the input and a red asterisk on the right side of label
  rightSection (React.ReactNode) — Content section displayed on the right side of the input
  rightSectionPointerEvents (React.CSSProperties[\"pointerEvents\"]) [default 'none'] — Sets <code>pointer-events</code> styles on the <code>rightSection</code> element. Use <code>'all'</code> when section contains interactive elements (buttons, links).
  rightSectionProps (React.ComponentProps<\"div\">) — Props passed down to the <code>rightSection</code> element
  rightSectionWidth (React.CSSProperties[\"width\"]) — Right section width, used to set <code>width</code> of the section and input <code>padding-right</code>, by default equals to the input height
  size (MantineSize) [default 'sm'] — Controls input <code>height</code>, horizontal <code>padding</code>, and <code>font-size</code>
  success (React.ReactNode) — Contents of <code>Input.Success</code> component. If not set, success is not displayed.
  successProps (InputSuccessProps & DataAttributes) — Props passed down to the <code>Input.Success</code> component
  withAsterisk (boolean) [default false] — If set, the required asterisk is displayed next to the label. Overrides <code>required</code> prop. Does not add required attribute to the input.
  withErrorStyles (boolean) [default true] — Determines whether the input should have red border and red text color when the <code>error</code> prop is set
  withSuccessStyles (boolean) [default true] — Determines whether the input should have green border when the <code>success</code> prop is set
  wrapperProps (WrapperProps) — Props passed down to the root element

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory (f/controlled TextInput))
     :clj (f/not-implemented "mantine.core/text-input")))
