;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.hooks
  "Mantine @mantine/hooks 9.4.1 wrappers (generated).

Thin def-aliases over the JS hooks — raw passthrough in both directions.
Rules of hooks are NOT enforced here; they are delegated to React (call
only inside function components / other hooks). Object returns need ^js
or js-interop access under :advanced compilation."
  (:require
   #?@(:cljs [["@mantine/hooks" :refer [useClipboard useDisclosure useToggle]]])
   #?@(:clj [[mantine.impl.factory :as f]])))

(def use-clipboard
  "useClipboard — Copy to clipboard with feedback timeout

https://mantine.dev/hooks/use-clipboard

Raw passthrough of the JS hook: pass JS-shaped args (#js {...}); returns
the raw JS value (tuples destructure positionally, object returns are read
via interop — use ^js under :advanced)."
  #?(:cljs useClipboard
     :clj (f/not-implemented "mantine.hooks/use-clipboard")))

(def use-disclosure
  "useDisclosure — Manages boolean state, provides open, close and toggle handlers, usually used with modals, drawers and popovers

https://mantine.dev/hooks/use-disclosure

Raw passthrough of the JS hook: pass JS-shaped args (#js {...}); returns
the raw JS value (tuples destructure positionally, object returns are read
via interop — use ^js under :advanced)."
  #?(:cljs useDisclosure
     :clj (f/not-implemented "mantine.hooks/use-disclosure")))

(def use-toggle
  "useToggle — Switches between given values

https://mantine.dev/hooks/use-toggle

Raw passthrough of the JS hook: pass JS-shaped args (#js {...}); returns
the raw JS value (tuples destructure positionally, object returns are read
via interop — use ^js under :advanced)."
  #?(:cljs useToggle
     :clj (f/not-implemented "mantine.hooks/use-toggle")))
