;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.modals
  "Mantine @mantine/modals 9.4.1 wrappers (generated, supplement hoisted from codegen/supplements/)."
  (:require
   #?@(:cljs [["@mantine/modals" :refer [ModalsProvider openModal openConfirmModal openContextModal closeModal closeAllModals updateModal updateContextModal useModals]]
              [mantine.impl.props :as p]])
   [mantine.impl.factory :as f]))

(def modals-provider
  "ModalsProvider — Centralized modals manager with option to handle state of multi-step modals (Modals family)

https://mantine.dev/x/modals

Props (docgen 9.4.1):
  children (React.ReactNode) — Your app
  labels (ConfirmLabels) — Confirm modal labels
  modalProps (ModalSettings) — Shared Modal component props, applied for every modal
  modals (Record<string, FC<ContextModalProps<any>>>) — Predefined modals

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory ModalsProvider)
     :clj (f/not-implemented "mantine.modals/modals-provider")))

;; ---- hoisted from codegen/supplements/modals.cljc ----

(def provider
  "Alias for `modals-provider` — the ModalsProvider that must be mounted once
  (inside MantineProvider) for the imperative modal fns to display anything."
  modals-provider)

(defn open
  "Open a modal. The options map goes through the standard props converter
  (:title, :children, :size, :centered, ...); nested *Props supply JS-shaped
  values (shallow passthrough). Returns the modal id (raw string)."
  [data]
  #?(:cljs (openModal (p/convert data))
     :clj ((f/not-implemented "mantine.modals/open") data)))

(defn open-confirm-modal
  "Open a confirmation modal. Options map converted like `open`; :labels and
  :on-confirm / :on-cancel supply the confirm/cancel wiring. Returns the modal id."
  [data]
  #?(:cljs (openConfirmModal (p/convert data))
     :clj ((f/not-implemented "mantine.modals/open-confirm-modal") data)))

(defn open-context-modal
  "Open a context modal registered on the provider. Options map converted like
  `open`; :modal is the registry key (passed verbatim) and :inner-props is passed
  RAW to the registered component. Returns the modal id."
  [data]
  #?(:cljs (openContextModal (p/convert data))
     :clj ((f/not-implemented "mantine.modals/open-context-modal") data)))

(defn close
  "Close the modal with the given id (raw string in and out)."
  [id]
  #?(:cljs (closeModal id)
     :clj ((f/not-implemented "mantine.modals/close") id)))

(defn close-all
  "Close all open modals."
  []
  #?(:cljs (closeAllModals)
     :clj ((f/not-implemented "mantine.modals/close-all"))))

(defn update-modal
  "Update an open modal; matched by :id in the options map (converted like `open`)."
  [data]
  #?(:cljs (updateModal (p/convert data))
     :clj ((f/not-implemented "mantine.modals/update-modal") data)))

(defn update-context-modal
  "Update an open context modal; matched by :id in the options map (converted like
  `open`, with :inner-props passed RAW)."
  [data]
  #?(:cljs (updateContextModal (p/convert data))
     :clj ((f/not-implemented "mantine.modals/update-context-modal") data)))

(def use-modals
  "Reactive hook over the default modals store. Raw passthrough: returns the raw
  JS ModalsContext value (read via interop: .-modals, .-openModal, ...)."
  #?(:cljs useModals
     :clj (f/not-implemented "mantine.modals/use-modals")))