;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.notifications
  "Mantine @mantine/notifications 9.4.1 wrappers (generated, supplement hoisted from codegen/supplements/)."
  (:refer-clojure :exclude [update])
  (:require
   #?@(:cljs [["@mantine/notifications" :refer [Notifications showNotification hideNotification updateNotification cleanNotifications cleanNotificationsQueue useNotifications]]
              [mantine.impl.props :as p]])
   [mantine.impl.factory :as f]))

(def notifications
  "Notifications — Mantine notifications system

https://mantine.dev/x/notifications

Props (docgen 9.4.1):

- **allowDragDismiss** `boolean` _(default `true`)_ — Determines whether notifications can be dismissed by dragging left or right
- **allowScrollDismiss** `boolean` _(default `true`)_ — Determines whether notifications can be dismissed with horizontal scroll gesture while hovered
- **autoClose** `number | false` _(default `4000`)_ — Auto close timeout for all notifications in ms, `false` to disable auto close, can be overwritten for individual notifications in `notifications.show` function
- **containerWidth** `string | number` _(default `440`)_ — Notification width, cannot exceed 100%
- **limit** `number` _(default `5`)_ — Maximum number of notifications displayed at a time, other new notifications will be added to queue
- **notificationMaxHeight** `string | number` _(default `200`)_ — Notification `max-height`, used for transitions
- **pauseResetOnHover** `\"all\" | \"notification\"` _(default `'all'`)_ — Determines which notifications should pause auto close on hover, `'all'` – pauses auto close for all notifications when any notification is hovered, `'notification'` – pauses auto close only for the hovered notification
- **portalProps** `BasePortalProps` — Props passed down to the `Portal` component
- **position** `NotificationPosition` _(default `'bottom-right'`)_ — Notifications default position
- **store** `NotificationsStore` — Store for notifications state, can be used to create multiple instances of notifications system in your application
- **transitionDuration** `number` _(default `250`)_ — Notification transition duration in ms
- **withinPortal** `boolean` _(default `true`)_ — Determines whether notifications container should be rendered inside `Portal`
- **zIndex** `string | number` _(default `400`)_ — Notifications container z-index

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Notifications)
     :clj (f/not-implemented "mantine.notifications/notifications")))

;; ---- hoisted from codegen/supplements/notifications.cljc ----

(def provider
  "Alias for `notifications` — the renderer component that must be mounted once
  (inside MantineProvider) for the imperative notification fns to display anything."
  notifications)

(defn show
  "Show a notification. The options map goes through the standard props converter:
  :message (required), :title, :color, :icon, :loading, :radius, :auto-close,
  :position, :priority, :id, :on-close, :on-open, ... Returns the notification id."
  [data]
  #?(:cljs (showNotification (p/convert data))
     :clj ((f/not-implemented "mantine.notifications/show") data)))

(defn hide
  "Hide the notification with the given id (raw string in and out)."
  [id]
  #?(:cljs (hideNotification id)
     :clj ((f/not-implemented "mantine.notifications/hide") id)))

(defn update
  "Update a shown notification; matched by :id in the options map (converted like
  `show`). Returns the id."
  [data]
  #?(:cljs (updateNotification (p/convert data))
     :clj ((f/not-implemented "mantine.notifications/update") data)))

(defn clean
  "Remove all notifications — active and queued."
  []
  #?(:cljs (cleanNotifications)
     :clj ((f/not-implemented "mantine.notifications/clean"))))

(defn clean-queue
  "Remove only queued notifications (not yet shown)."
  []
  #?(:cljs (cleanNotificationsQueue)
     :clj ((f/not-implemented "mantine.notifications/clean-queue"))))

(def use-notifications
  "Reactive hook over the default notifications store. Raw passthrough: returns the
  raw JS NotificationsState (read via interop: .-notifications, .-queue, ...)."
  #?(:cljs useNotifications
     :clj (f/not-implemented "mantine.notifications/use-notifications")))