;; GENERATED by `bb generate` from the committed codegen inputs (Mantine 9.4.1) — DO NOT EDIT.
(ns mantine.spotlight
  "Mantine @mantine/spotlight 9.4.1 wrappers (generated, supplement hoisted from codegen/supplements/)."
  (:require
   #?@(:cljs [["@mantine/spotlight" :refer [Spotlight SpotlightAction SpotlightActionsGroup SpotlightRoot SpotlightSearch openSpotlight closeSpotlight toggleSpotlight useSpotlight SpotlightActionsList SpotlightEmpty SpotlightFooter]]])
   [mantine.impl.factory :as f]))

(def spotlight
  "Spotlight — Command center for your application

https://mantine.dev/x/spotlight

Props (docgen 9.4.1):

- **actions** `SpotlightActions[]` **(required)** — Actions data, passed down to `Spotlight.Action` component
- **centered** `boolean` _(default `false`)_ — If set, the modal is centered vertically
- **children** `React.ReactNode` — Modal content
- **clearQueryOnClose** `boolean` _(default `true`)_ — Determines whether the search query should be cleared when the spotlight is closed
- **closeOnActionTrigger** `boolean` _(default `true`)_ — Determines whether spotlight should be closed when one of the actions is triggered
- **closeOnClickOutside** `boolean` _(default `true`)_ — If set, the modal/drawer is closed when user clicks on the overlay
- **closeOnEscape** `boolean` _(default `true`)_ — If set, `onClose` is called when user presses the escape key
- **disabled** `boolean` — If set, spotlight will not be rendered
- **filter** `SpotlightFilterFunction` — Function to filter actions data based on search query, by default actions are filtered by title, description and keywords
- **forceOpened** `boolean` — Forces opened state, useful for tests
- **fullScreen** `boolean` _(default `false`)_ — If set, the modal takes the entire screen
- **highlightQuery** `boolean` _(default `false`)_ — Determines whether search query should be highlighted in action label
- **id** `string` — Id used to connect modal/drawer with body and title
- **keepMounted** `boolean` _(default `false`)_ — If set modal/drawer is not unmounted from the DOM when hidden. `display: none` styles are applied instead.
- **limit** `number` _(default `Infinity`)_ — Maximum number of actions displayed at a time
- **lockScroll** `boolean` _(default `true`)_ — If set, scroll is locked when `opened={true}`
- **maxHeight** `MaxHeight<string | number>` _(default `400`)_ — Spotlight content max-height. Ignored unless `scrollable` prop is set.
- **nothingFound** `React.ReactNode` — Message displayed when none of the actions match given `filter`
- **onEnterTransitionEnd** `() => void` — Called when enter transition ends
- **onExitTransitionEnd** `() => void` — Called when exit transition ends
- **onQueryChange** `(query: string) => void` — Called when query changes
- **onSpotlightClose** `() => void` — Called when spotlight closes
- **onSpotlightOpen** `() => void` — Called when spotlight opens
- **overlayProps** `ModalBaseOverlayProps` — Props passed down to the `Overlay` component, use to configure opacity, `background-color`, styles and other properties
- **padding** `MantineSpacing` _(default `'md'`)_ — Key of `theme.spacing` or any valid CSS value to set content, header and footer padding
- **portalProps** `BasePortalProps` — Props passed down to the Portal component when `withinPortal` is set
- **query** `string` — Controlled Spotlight search query
- **radius** `MantineRadius | number` _(default `theme.defaultRadius`)_ — Key of `theme.radius` or any valid CSS value to set `border-radius`
- **removeScrollProps** `RemoveScrollProps` — Props passed down to react-remove-scroll, can be used to customize scroll lock behavior
- **returnFocus** `boolean` _(default `true`)_ — If set, focus is returned to the last active element when `onClose` is called
- **scrollAreaComponent** `ScrollAreaComponent` _(default `'div'`)_ — Scroll area component
- **scrollAreaProps** `Partial<ScrollAreaAutosizeProps>` — Props passed down to the `ScrollArea` component
- **scrollable** `boolean` _(default `false`)_ — Determines whether the actions list should be scrollable. If not set, `maxHeight` is ignored
- **searchProps** `SpotlightSearchProps` — Props passed down to the `Spotlight.Search`
- **shadow** `MantineShadow` _(default `'xl'`)_ — Key of `theme.shadows` or any valid CSS box-shadow value
- **shortcut** `string | string[] | null` _(default `'mod + K'`)_ — Keyboard shortcut or a list of shortcuts to trigger spotlight
- **size** `MantineSize | number` _(default `'md'`)_ — Controls width of the content area
- **stackId** `string` — Id of the modal in the `Modal.Stack`
- **store** `SpotlightStore` — Spotlight store, can be used to create multiple instances of spotlight
- **tagsToIgnore** `string[]` _(default `['input', 'textarea', 'select']`)_ — A list of tags which when focused will be ignored by shortcut
- **title** `React.ReactNode` — Modal title
- **transitionProps** `TransitionProps` — Props added to the `Transition` component that used to animate overlay and body, use to configure duration and animation type, `{ duration: 200, transition: 'fade-down' }` by default
- **trapFocus** `boolean` _(default `true`)_ — If set, focus is trapped within the modal/drawer
- **triggerOnContentEditable** `boolean` _(default `false`)_ — Determines whether shortcut should trigger based in contentEditable
- **withOverlay** `boolean` _(default `true`)_ — If set, the overlay is rendered
- **withinPortal** `boolean` _(default `true`)_ — If set, the component is rendered inside `Portal`
- **xOffset** `MarginLeft<string | number>` _(default `5vw`)_ — Left/right modal offset
- **yOffset** `MarginTop<string | number>` _(default `5dvh`)_ — Top/bottom modal offset
- **zIndex** `string | number` _(default `200`)_ — `z-index` CSS property of the root element

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory Spotlight)
     :clj (f/not-implemented "mantine.spotlight/spotlight")))

(def spotlight-action
  "SpotlightAction — Command center for your application (Spotlight family)

https://mantine.dev/x/spotlight

Props (docgen 9.4.1):

- **children** `React.ReactNode` — Children override default action elements, if passed, label, description and sections are hidden
- **closeSpotlightOnTrigger** `boolean` — Determines whether the spotlight should be closed when action is triggered, overrides `closeOnActionTrigger` prop set on `Spotlight`
- **description** `string` — Action description, pass string to use in default filter
- **dimmedSections** `boolean` _(default `true`)_ — Determines whether left and right sections should have dimmed styles
- **highlightColor** `MantineColor` _(default `'yellow'`)_ — Key of `theme.colors` of any valid CSS color that will be used to highlight search query
- **highlightQuery** `boolean` _(default `false`)_ — Determines whether search query should be highlighted in action label
- **keywords** `string | string[]` — Keywords that are used for default filtering, not displayed anywhere, can be a string: \"react,router,javascript\" or an array: ['react', 'router', 'javascript']
- **label** `string` — Action label, pass string to use in default filter
- **leftSection** `React.ReactNode` — Section displayed on the left side of the label, for example, icon
- **rightSection** `React.ReactNode` — Section displayed on the right side of the label, for example, hotkey

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightAction)
     :clj (f/not-implemented "mantine.spotlight/spotlight-action")))

(def spotlight-actions-group
  "SpotlightActionsGroup — Command center for your application (Spotlight family)

https://mantine.dev/x/spotlight

Props (docgen 9.4.1):

- **children** `React.ReactNode` — `Spotlight.Action` components
- **label** `string` — Group label

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightActionsGroup)
     :clj (f/not-implemented "mantine.spotlight/spotlight-actions-group")))

(def spotlight-root
  "SpotlightRoot — Command center for your application (Spotlight family)

https://mantine.dev/x/spotlight

Props (docgen 9.4.1):

- **centered** `boolean` _(default `false`)_ — If set, the modal is centered vertically
- **children** `React.ReactNode` — Modal content
- **clearQueryOnClose** `boolean` _(default `true`)_ — Determines whether the search query should be cleared when the spotlight is closed
- **closeOnActionTrigger** `boolean` _(default `true`)_ — Determines whether spotlight should be closed when one of the actions is triggered
- **closeOnClickOutside** `boolean` _(default `true`)_ — If set, the modal/drawer is closed when user clicks on the overlay
- **closeOnEscape** `boolean` _(default `true`)_ — If set, `onClose` is called when user presses the escape key
- **disabled** `boolean` — If set, spotlight will not be rendered
- **forceOpened** `boolean` — Forces opened state, useful for tests
- **fullScreen** `boolean` _(default `false`)_ — If set, the modal takes the entire screen
- **id** `string` — Id used to connect modal/drawer with body and title
- **keepMounted** `boolean` _(default `false`)_ — If set modal/drawer is not unmounted from the DOM when hidden. `display: none` styles are applied instead.
- **lockScroll** `boolean` _(default `true`)_ — If set, scroll is locked when `opened={true}`
- **maxHeight** `MaxHeight<string | number>` _(default `400`)_ — Spotlight content max-height. Ignored unless `scrollable` prop is set.
- **onEnterTransitionEnd** `() => void` — Called when enter transition ends
- **onExitTransitionEnd** `() => void` — Called when exit transition ends
- **onQueryChange** `(query: string) => void` — Called when query changes
- **onSpotlightClose** `() => void` — Called when spotlight closes
- **onSpotlightOpen** `() => void` — Called when spotlight opens
- **overlayProps** `ModalBaseOverlayProps` — Props passed down to the `Overlay` component, use to configure opacity, `background-color`, styles and other properties
- **padding** `MantineSpacing` _(default `'md'`)_ — Key of `theme.spacing` or any valid CSS value to set content, header and footer padding
- **portalProps** `BasePortalProps` — Props passed down to the Portal component when `withinPortal` is set
- **query** `string` — Controlled Spotlight search query
- **radius** `MantineRadius | number` _(default `theme.defaultRadius`)_ — Key of `theme.radius` or any valid CSS value to set `border-radius`
- **removeScrollProps** `RemoveScrollProps` — Props passed down to react-remove-scroll, can be used to customize scroll lock behavior
- **returnFocus** `boolean` _(default `true`)_ — If set, focus is returned to the last active element when `onClose` is called
- **scrollAreaComponent** `ScrollAreaComponent` _(default `'div'`)_ — Scroll area component
- **scrollable** `boolean` _(default `false`)_ — Determines whether the actions list should be scrollable. If not set, `maxHeight` is ignored
- **shadow** `MantineShadow` _(default `'xl'`)_ — Key of `theme.shadows` or any valid CSS box-shadow value
- **shortcut** `string | string[] | null` _(default `'mod + K'`)_ — Keyboard shortcut or a list of shortcuts to trigger spotlight
- **size** `MantineSize | number` _(default `'md'`)_ — Controls width of the content area
- **stackId** `string` — Id of the modal in the `Modal.Stack`
- **store** `SpotlightStore` — Spotlight store, can be used to create multiple instances of spotlight
- **tagsToIgnore** `string[]` _(default `['input', 'textarea', 'select']`)_ — A list of tags which when focused will be ignored by shortcut
- **title** `React.ReactNode` — Modal title
- **transitionProps** `TransitionProps` — Props added to the `Transition` component that used to animate overlay and body, use to configure duration and animation type, `{ duration: 200, transition: 'fade-down' }` by default
- **trapFocus** `boolean` _(default `true`)_ — If set, focus is trapped within the modal/drawer
- **triggerOnContentEditable** `boolean` _(default `false`)_ — Determines whether shortcut should trigger based in contentEditable
- **withOverlay** `boolean` _(default `true`)_ — If set, the overlay is rendered
- **withinPortal** `boolean` _(default `true`)_ — If set, the component is rendered inside `Portal`
- **xOffset** `MarginLeft<string | number>` _(default `5vw`)_ — Left/right modal offset
- **yOffset** `MarginTop<string | number>` _(default `5dvh`)_ — Top/bottom modal offset
- **zIndex** `string | number` _(default `200`)_ — `z-index` CSS property of the root element

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightRoot)
     :clj (f/not-implemented "mantine.spotlight/spotlight-root")))

(def spotlight-search
  "SpotlightSearch — Command center for your application (Spotlight family)

https://mantine.dev/x/spotlight

Props (docgen 9.4.1):

- **disabled** `boolean` — Sets `disabled` attribute on the `input` element
- **error** `React.ReactNode` — Determines whether the input should have error styles and `aria-invalid` attribute
- **id** `string` — Input element id
- **inputSize** `string` — HTML `size` attribute for the input element (number of visible characters)
- **leftSection** `React.ReactNode` — Content section displayed on the left side of the input
- **leftSectionPointerEvents** `React.CSSProperties[\"pointerEvents\"]` _(default `'none'`)_ — Sets `pointer-events` styles on the `leftSection` element. Use `'all'` when section contains interactive elements (buttons, links).
- **leftSectionProps** `React.ComponentProps<\"div\">` — Props passed down to the `leftSection` element
- **leftSectionWidth** `React.CSSProperties[\"width\"]` — Left section width, used to set `width` of the section and input `padding-left`, by default equals to the input height
- **loading** `boolean` _(default `false`)_ — Displays loading indicator in the left or right section
- **loadingPosition** `\"left\" | \"right\"` _(default `'right'`)_ — Position of the loading indicator
- **multiline** `boolean` _(default `false`)_ — Adjusts padding and sizing calculations for multiline inputs (use with `component=\"textarea\"`). Does not make the input multiline by itself.
- **pointer** `boolean` _(default `false`)_ — Determines whether the input should have `cursor: pointer` style. Use when input acts as a button-like trigger (e.g., `component=\"button\"` for Select/DatePicker).
- **radius** `MantineRadius | number` _(default `theme.defaultRadius`)_ — Key of `theme.radius` or any valid CSS value to set `border-radius`, numbers are converted to rem
- **required** `boolean` — Sets `required` attribute on the `input` element
- **rightSection** `React.ReactNode` — Content section displayed on the right side of the input
- **rightSectionPointerEvents** `React.CSSProperties[\"pointerEvents\"]` _(default `'none'`)_ — Sets `pointer-events` styles on the `rightSection` element. Use `'all'` when section contains interactive elements (buttons, links).
- **rightSectionProps** `React.ComponentProps<\"div\">` — Props passed down to the `rightSection` element
- **rightSectionWidth** `React.CSSProperties[\"width\"]` — Right section width, used to set `width` of the section and input `padding-right`, by default equals to the input height
- **rootRef** `Ref<HTMLDivElement>` — Root element ref
- **size** `MantineSize` _(default `'sm'`)_ — Controls input `height`, horizontal `padding`, and `font-size`
- **success** `React.ReactNode` — Determines whether the input should have success styles
- **withAria** `boolean` _(default `true`)_ — Determines whether `aria-` and other accessibility attributes should be added to the input. Only disable when implementing custom accessibility handling.
- **withErrorStyles** `boolean` _(default `true`)_ — Determines whether the input should have red border and red text color when the `error` prop is set
- **withSuccessStyles** `boolean` _(default `true`)_ — Determines whether the input should have green border when the `success` prop is set
- **wrapperProps** `WrapperProps` — Props passed down to the root element of the `Input` component

Optional leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightSearch)
     :clj (f/not-implemented "mantine.spotlight/spotlight-search")))

;; ---- hoisted from codegen/supplements/spotlight.cljc ----

(defn open
  "Open the spotlight command palette (single default instance)."
  []
  #?(:cljs (openSpotlight)
     :clj ((f/not-implemented "mantine.spotlight/open"))))

(defn close
  "Close the spotlight command palette."
  []
  #?(:cljs (closeSpotlight)
     :clj ((f/not-implemented "mantine.spotlight/close"))))

(defn toggle
  "Toggle the spotlight command palette open/closed."
  []
  #?(:cljs (toggleSpotlight)
     :clj ((f/not-implemented "mantine.spotlight/toggle"))))

(def use-spotlight
  "Reactive hook over the default spotlight store. Raw passthrough: returns the raw
  JS spotlight store value (read via interop: .-opened, .-open, ...)."
  #?(:cljs useSpotlight
     :clj (f/not-implemented "mantine.spotlight/use-spotlight")))

;; ---- compound parts (dot-notation subcomponents docgen omits) ----

(def spotlight-actions-list
  "Spotlight.ActionsList — compound part of Spotlight (docgen omits it). Optional
  leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightActionsList)
     :clj (f/not-implemented "mantine.spotlight/spotlight-actions-list")))

(def spotlight-empty
  "Spotlight.Empty — compound part of Spotlight (docgen omits it). Optional
  leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightEmpty)
     :clj (f/not-implemented "mantine.spotlight/spotlight-empty")))

(def spotlight-footer
  "Spotlight.Footer — compound part of Spotlight (docgen omits it). Optional
  leading props map; remaining args are children."
  #?(:cljs (f/factory SpotlightFooter)
     :clj (f/not-implemented "mantine.spotlight/spotlight-footer")))