;; Per-version-bump input refresh: extracts the committed generator inputs from a
;; Mantine source checkout (pinned 9.4.1). Run AFTER the clone has run docgen:
;;
;;   git clone --depth 1 --branch 9.4.1 https://github.com/mantinedev/mantine <dir>
;;   cd <dir> && yarn install && yarn tsx scripts/docgen
;;   bb extract <dir>
;;
;; Writes (all committed):
;;   codegen/input/docgen.json         — verbatim copy of the docgen output
;;   codegen/input/hook-docs.edn       — {"useX" "description"} from mdx-hooks-data.ts
;;   codegen/input/component-docs.edn  — {"Button" {:description ... :slug ... :polymorphic ...}}
;;                                       (extension packages are keyed by docs-entry name;
;;                                        join via :props, which lists the docgen keys)
;;   codegen/input/mantine-version.edn — {:mantine-version ...} provenance witness (ADR 0005)
(ns extract
  (:require [anchor]
            [babashka.fs :as fs]
            [cheshire.core :as json]
            [clojure.string :as str]))

(def clone-dir
  (or (first *command-line-args*)
      (throw (ex-info "usage: bb extract <mantine-clone-dir>" {}))))

(defn- clone-mantine-version
  "The Mantine version the fed clone actually is — @mantine/core's package.json version,
  falling back to the clone-dir root package.json."
  []
  (let [core-pkg (fs/path clone-dir "packages/@mantine/core/package.json")
        pkg (if (fs/exists? core-pkg) core-pkg (fs/path clone-dir "package.json"))]
    (get (json/parse-string (slurp (str pkg))) "version")))

(def mdx-dir (fs/path clone-dir "apps/mantine.dev/src/mdx/data"))

;; --- hooks: hDocs('useX', 'description') calls + inline-object exceptions ------------

(defn extract-hook-docs [text]
  (let [hdocs (re-seq #"(?s)(use\w+): hDocs\(\s*'use\w+',\s*'([^']*)'\s*\)" text)
        ;; inline-object entries (e.g. useElementSize) — no nested braces in this file
        inline (for [[_ nm block] (re-seq #"(?s)(use\w+): \{([^{}]*)\}" text)
                     :let [d (second (re-find #"description: '([^']*)'" block))]
                     :when d]
                 [nm d])]
    (into (sorted-map)
          (concat (for [[_ nm d] hdocs]
                    [nm (str/replace d #"\s+" " ")])
                  inline))))

;; --- components: inline object literals keyed by exact PascalCase docgen name --------
;; Same parse Mantine's own scripts/llm/compile-mcp-data.ts uses (verified regex-safe).

(defn extract-component-docs [text]
  (into (sorted-map)
        (for [[_ nm block] (re-seq #"(?s)(\w+): \{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}" text)
              :let [field (fn [k] (second (re-find (re-pattern (str k ": '([^']*)'")) block)))
                    description (field "description")
                    package (second (re-find #"package: '(@mantine/[^']+)'" block))
                    props (some->> (re-find #"(?s)props: \[([^\]]*)\]" block)
                                   second
                                   (re-seq #"'([^']+)'")
                                   (mapv second))]
              ;; landing pages (CorePackage, GettingStarted*) carry no package/props
              :when (and package (seq props))]
          [nm (cond-> {:description description
                       :package package
                       :slug (field "slug")
                       :props props}
                (re-find #"polymorphic: true" block) (assoc :polymorphic true))])))

(let [out (fs/path "codegen" "input")
      anchor-v (anchor/anchor-version)
      clone-v (clone-mantine-version)]
  (when (not= clone-v anchor-v)
    (throw (ex-info (str "clone Mantine version " clone-v " != anchor " anchor-v
                         " — extract the clone pinned to the anchor, or bump package.json first.")
                    {:clone clone-v :anchor anchor-v})))
  (fs/create-dirs out)
  (fs/copy (fs/path clone-dir "apps/mantine.dev/src/.docgen/docgen.json")
           (fs/path out "docgen.json")
           {:replace-existing true})
  (let [hooks (extract-hook-docs (slurp (str (fs/path mdx-dir "mdx-hooks-data.ts"))))]
    (spit (str (fs/path out "hook-docs.edn"))
          (with-out-str
            (println (str ";; GENERATED by `bb extract` from mdx-hooks-data.ts (Mantine " anchor-v ") — do not edit."))
            (prn hooks)))
    (println "hook-docs.edn:" (count hooks) "hooks"))
  (let [components (apply merge
                          (for [f ["mdx-core-data.ts" "mdx-dates-data.ts" "mdx-charts-data.ts" "mdx-others-data.ts"]]
                            (extract-component-docs (slurp (str (fs/path mdx-dir f))))))]
    (spit (str (fs/path out "component-docs.edn"))
          (with-out-str
            (println (str ";; GENERATED by `bb extract` from mdx-{core,dates,charts}-data.ts (Mantine " anchor-v ") — do not edit."))
            (prn (into (sorted-map) components))))
    (println "component-docs.edn:" (count components) "components"))
  (spit (str (fs/path out "mantine-version.edn"))
        (with-out-str
          (println (str ";; GENERATED by `bb extract` — the Mantine anchor the committed inputs were captured at. Do not edit."))
          (prn {:mantine-version anchor-v})))
  (println "mantine-version.edn:" anchor-v)
  (println "docgen.json copied."))
